### ISSUE TITLE
Can't style it at all

### ISSUE THREAD

**Issue by Jakobud** [jacoborus/nanobar#24]
You put all the styles inline in the HTML and now you can't style the bar or container at all. What is the point of setting the ID attribute if you can't use it to set styles? Can't adjust the height, etc...

**Comment by gamecubate** [comment]
Pending a merge of one of the pull requests that addresses that, you can always style like this:
```
#my-nanobar-container div div {
  background-color: #05366E!important;
}
```

**Comment by parthakkar** [comment]
Another way is to just edit the JS

`cssCont = {
				width: '100%',
				**height: '10px'**, // Default is 4px
				zIndex: 9999,
				top : '0'
			},`

**Comment by parthakkar** [comment]
Even though I have a target div, my nanobar still appears globally - anybody face a similar issue?

**Comment by jacoborus** [comment]
You can now edit all CSS styles. The classnames are `.nanobar` and `.nanobar .bar`
