### ISSUE TITLE
Allow overwrite CSS

### ISSUE THREAD

**Issue by dgerding** [jacoborus/nanobar#26]
Hi,
Thanks for sharing this cool control.  I tried a couple of css styles but they didn't work... just wondering if I can/should be able to have the nanobar centered in the div so that it fills in/grows "from the middle" instead of from the left.

Any ideas appreciated.

Thanks,
Dave G

**Comment by jacoborus** [comment]
Hi Dave,
I'm going to add an extra option that overwrites all css. I'm on holidays right now, just give me a week to get back to work

**Comment by dgerding** [comment]
Wow.. Thanks!  Happy New Year

On Jan 4, 2015 7:38 PM, Jacobo Tabernero <notifications@github.com> wrote:

Hi Dave,
I'm going to add an extra option that overwrites all css. I'm on holidays right now, just give me a week to get back to work

**Comment by dgerding** [comment]
Hi Jacobo, thanks again for offering to make CSS adaptable/changeable. I can't tell if you already have pushed those changes. Let me know if you're able to get around to it and thanks again.

Dave G

On Jan 4, 2015 6:38 PM, Jacobo Tabernero <notifications@github.com> wrote:

Hi Dave,
I'm going to add an extra option that overwrites all css. I'm on holidays right now, just give me a week to get back to work

**Comment by jacoborus** [comment]
All the CSS styles are now overwritable
