### ISSUE TITLE
multiple bars get created when repeatedly calling go(100)

### ISSUE THREAD

**Issue by stuikomma** [jacoborus/nanobar#31]
Hi,

In my project I want to use the nanobar whenever the user causes some (potentially long-running) calculations. However, some of them end really quickly and the user can click as often as they want. In this case multiple bars appear that are layouted below one another. Eventually this could fill the whole screen.

This should be avoided, e.g. by removing the previous bar without an animation,

You can also try this on the demo page by repeatedly clicking the button `nanobar.go(100)`.

**Comment by jacoborus** [comment]
hi @stuikomma , what browser?

**Comment by stuikomma** [comment]
Chrome

**Comment by stuikomma** [comment]
But it's the same in Firefox.

**Comment by adius** [comment]
yeah, this sucks. +1

**Comment by skibz** [comment]
@stuikomma , why not just throttle the button clicks?

**Comment by stuikomma** [comment]
@skibz Because it is a user interaction? Usually, they wouldn't do that but they might. +I think that this is something that should be handled by the library.

**Comment by yoonwaiyan** [comment]
I think it's a good idea to check for multiple bars in the library too, I'm calling the Nanobar when there's an ajax call, if there are more than one ajax call in one single js it will displays multiple bars.

**Comment by gamecubate** [comment]
Old issue that but I've only been using nanobar for a few weeks.

I don't think that that's a nanobar concern. Nanobar is a view that draws (and animates) itself according to some (target) value. Why complexify it? I agree with @skibz. Just let the user throttle his calls.

On that note, however, I find it disappointing that one can only (apparently) have one nanobar per document. That IMO is a far greater limitation of the current setup.

**Comment by jacoborus** [comment]
Hi guys, this is the natural behaviour of nanobar, it creates a progress bar everytime the previous bar has reached 100%. You can create multiple nanobars for multiple progresses. You can also edit nanobar css from the last commit.
