### ISSUE TITLE
Add "trickle" option.

### ISSUE THREAD

**Issue by DylanPiercey** [jacoborus/nanobar#36]
With nprogress (my current progress bar of choice) you can `.start()` the progress bar which will cause it to trickle along indefinetly until you call `.done()`.

This is extremely handy for representing tasks which are difficult to measure.
Is this something that could be added?

**Comment by curioustechizen** [comment]
+1 for this feature request. I am looking for indeterminate progress bars as well.

**Comment by MrHmP** [comment]
What would an "indeterminate progress" would look like? Any ideas which will help me implementing it?

**Comment by DylanPiercey** [comment]
Check out https://github.com/rstacruz/nprogress. Basically it just trickles along at random and never finishes.

**Comment by jacoborus** [comment]
Hi guys, that's a nice feature, but I want to keep nanobar as minimal as possible. If you want to use the "trickle" options I recommend you to keep using nProgress or maybe implement its `inc` method on your nanobar instance (https://github.com/rstacruz/nprogress/blob/6de3a45c33fe1f142b73935206a6f1e74a230a3f/nprogress.js#L158-L188)
