### ISSUE TITLE
nanobar.go(0)

### ISSUE THREAD

**Issue by s-kias** [jacoborus/nanobar#37]
I want to let nanobar go back to 0 and disapper instead of going to 100 when an ajax request is failed.
But when I excute nanobar.go(0) it doesn't make a different

**Comment by parthakkar** [comment]
Anybody ever resolve this?

**Comment by MaXwellFalstein** [comment]
Not that I am aware of. I could be wrong.

**Comment by MrHmP** [comment]
Fixed
