### ISSUE TITLE
Way to fetch current status of nanobar

### ISSUE THREAD

**Issue by vishwaabhinav** [jacoborus/nanobar#39]
Can you add an method to fetch current completion status of nanobar? Is there a way to do it now in any way?

**Comment by MrHmP** [comment]
You can use nanobar.bars[0].width

**Comment by jacoborus** [comment]
Hi @vishwaabhinav , what do you mean with "current status of nanobar"?

**Comment by vishwaabhinav** [comment]
Hi,
Sorry if I wasn't very clear in my description.
By status, I mean how much container width it is occupying. 
Solution suggested by @MrHmP will work, but is it viable to expose a method such as `nanobar.getCompletionStatus()` which will return completion status(width essentially) of different nanobars in, say an object `{key:id, value:width}`?

And thanks for the awesome work, we are using nanobar very extensively in our projects since it is so lightweight and looks pretty cool.

**Comment by jacoborus** [comment]
I'm afraid that `nanobar.bars[0].width` solution is not working anymore since the last update. But you can wrap nanobar in a function that catches when `100` is passed to `go` method
