### ISSUE TITLE
Releases question

### ISSUE THREAD

**Issue by robertvrabel** [jacoborus/nanobar#42]
It looks like the release list here: https://github.com/jacoborus/nanobar/releases is out of date. Is there a reason the new releases aren't being tagged on github? I noticed in https://www.npmjs.com/package/nanobar it refers to the newest version as 0.4.0.

Basically my issue was I was trying to use version 0.2.0 when i was looking at the release list which i thought was the newest version, but was actually pretty outdated.

**Comment by jacoborus** [comment]
I just updated de bower package to the last version. Let me know if still having the problem please.

Closing this issue
