### ISSUE TITLE
Nanobar is not removed when attached to an element

### ISSUE THREAD

**Issue by butchero** [jacoborus/nanobar#43]
Hello,

I have notice, that when the nanobar is attached to an element (div), the created nanobar is not removed from dom, after .go(100), is just hidden.
This is annoying, because the bars created are pushing my elements down.

**Comment by butchero** [comment]
"new Nanobar()" was inside a click action, and it was created every time the button was pushed.

**Comment by jacoborus** [comment]
I was just trying to reproduce the error without success. Glad you resolved the problem

**Comment by butchero** [comment]
It was inside an ajax call, the new Nanobar().

Thx for your quick reply!
