### ISSUE TITLE
Bars stack when triggered before transition ends

### ISSUE THREAD

**Issue by claviska** [jacoborus/nanobar#47]
If you call `nanobar.go(100)` and then call `nanobar.go(50)` one or more times before the transition ends, you'll see the bars stack. It looks like `init()` is creating the bar and appending it to the target and doesn't check for the existence of another bar.

Example:

![2016-05-18 10 10 01](https://cloud.githubusercontent.com/assets/55639/15361730/b8a8ae88-1ce0-11e6-8f23-dd5810ae934b.gif)

I'm not sure what your preferred solution is, but I have a few ideas to toss around:
1. Empty the target element before calling [`el.appendChild()`](https://github.com/jacoborus/nanobar/blob/master/nanobar.js#L108).
2. Check for an existing bar. If one exists, use that instead (might look funny since the transition would animate backwards; might be able to disable the transition on the fly to prevent that behavior).
3. Provide a `reset()` method to programmatically remove the bar without animation.
4. Apply `overflow: hidden` to the `.nanobar` container (more of a stop gap than a real fix)

I don't think this is an edge case since it's not abnormal for apps to send consecutive asynchronous requests. Not having a programmatic way to reset progress before the transition ends is a bit of a shortcoming. (The only other option is to wait until the transition ends to start the next request.)

Happy to help out with this if you have any feedback or other ideas on it. Which approach do you think is best?

**Comment by nishant-chaturvedi** [comment]
A simple workaround of this problem using css:

```css
.nanobar .bar{
    position: absolute;
    top: 0;
    left: 0;
}
```

**Comment by claviska** [comment]
Idea 4 (`overflow: hidden`) is an easier quick fix, but it doesn't resolve the issue properly.

**Comment by jacoborus** [comment]
Sorry guys, but this is the expected behavior. If you don't like how the bar disappears you can change the transition animation with css:

```css
.nanobar .bar {
   transition: height .1s;
}
```

**Comment by claviska** [comment]
This is a stacking issue, not a transition issue. Additional bars get appended before existing ones are removed.

Please review the issue more closely and let me know what you think.

**Comment by brookstudio** [comment]
I met this issue today when I tried to use it during ajax calls in angular application. This should not be a closed issue. I made a trick to avoid the stack bars by adding the following code at the beginning of the "move" function 
`if (el.previousSibling) {
     el.previousSibling.style.height = 0;
 }`

**Comment by pir8radio** [comment]
I just reported a similar issue here, not sure who's this is...    https://github.com/jacoborus/nanobar/issues/61

but im seeing bars stack after i do a go 100...    its a setInterval, so the bars just keep stacking up...  

`<script> var nanobar = new Nanobar(); setInterval(function () { nanobar.go(65); $('#update_pending').load(location.href + ' #update_pending'); $(document).ajaxComplete(function () { nanobar.go(100); //progress 100 after ajax update complete }); }, 10000); //update every X ms. </script>` 

![image](https://user-images.githubusercontent.com/16748696/151864984-ed75fb3c-4754-42ec-a749-131692e80634.png)


![image](https://user-images.githubusercontent.com/16748696/151865007-d5076e31-cef5-41ef-8e61-0bf9336ef76b.png)
